### ISSUE TITLE
Fetch kernel version in BCC and pass to remote (BCC side issue)

### ISSUE THREAD

**Issue by joelagnel** [joelagnel/bpfd#13]
Currently the kernel version passed to bpf_prog_load from the BCC host is hardcoded and passed to the remote BPFd using the -k option. This is a horrible hack, fix it.

https://github.com/joelagnel/bcc/blob/bcc-bpfd/src/python/bcc/remote/adb.py#L40

**Comment by jcanseco** [comment]
We should close this issue. We investigated this in person and it turned out to not be an issue. 

I will put up a PR soon that removes the -k flag handling on BPFd since it's no longer needed.
