### ISSUE TITLE
missing README file and project description 

### ISSUE THREAD

**Issue by aalemayhu** [joelagnel/bpfd#5]
I guess it's easy to just read the Makefile, but having some short instructions would make it even easier for people to try out your project. Please consider adding those, thanks.

**Comment by joelagnel** [comment]
Thanks for creating this issue. I was about to. This project is only a few weeks old. I am working on an article on howto build and run this which is taking up my time. Once the article is published which should be in a few days, I will create a README (which will basically have the same contents). Stay tuned, thanks!

**Comment by joelagnel** [comment]
Fixed. Please check and reopen if needed!

**Comment by aalemayhu** [comment]
LGTM, thanks.
